<?php
$layout       = 'app';
$pageTitle    = 'Suggest Skills with AI';
$sidebarItems = adminSidebar('settings');
$breadcrumbs  = [
    ['label' => 'Admin', 'url' => '/admin'],
    ['label' => 'Settings', 'url' => '/admin/settings'],
    ['label' => 'Agent Skills', 'url' => '/admin/skills'],
    ['label' => 'Suggest with AI'],
];
?>
<div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="fw-bold mb-0"><i class="bi bi-magic me-2 text-primary"></i>AI Skill Suggestions</h2>
    <a href="/admin/skills" class="btn btn-outline-secondary">
        <i class="bi bi-arrow-left me-1"></i>Back
    </a>
</div>

<div class="alert alert-info">
    <i class="bi bi-info-circle me-1"></i>
    These suggestions were generated by your configured AI provider based on your
    <strong>organization type</strong>, your <strong>ticket types</strong>, and your <strong>groups</strong>.
    Skills that already exist in your setup were excluded. Check the ones you want to add, tweak the
    name or description if you like, and pick an owning group (or leave as Global). Then click
    <strong>Add Selected Skills</strong>.
</div>

<?php
$mode        = $mode ?? 'basic';
$sampleSize  = (int) ($sampleSize ?? 0);
$minedCount  = (int) ($minedCount ?? 0);
$regenerateHref = $mode === 'mine'
    ? '/admin/skills/suggest?mode=mine&n=' . $sampleSize
    : '/admin/skills/suggest?mode=basic';
?>
<div class="card border-0 shadow-sm mb-4">
    <div class="card-body p-3">
        <div class="row g-3 small">
            <div class="col-md-3">
                <div class="text-muted text-uppercase small fw-semibold mb-1">Organization Type</div>
                <div><i class="bi bi-building me-1 text-muted"></i><?= e($orgLabel) ?></div>
            </div>
            <div class="col-md-3">
                <div class="text-muted text-uppercase small fw-semibold mb-1">Ticket Types (<?= count($ticketTypes) ?>)</div>
                <?php if (empty($ticketTypes)): ?>
                    <span class="text-muted">None defined</span>
                <?php else: ?>
                    <?php foreach ($ticketTypes as $tt): ?>
                        <span class="badge bg-info bg-opacity-10 text-info me-1 mb-1"><?= e($tt['name']) ?></span>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="col-md-3">
                <div class="text-muted text-uppercase small fw-semibold mb-1">Groups (<?= count($groups) ?>)</div>
                <?php if (empty($groups)): ?>
                    <span class="text-muted">None defined</span>
                <?php else: ?>
                    <?php foreach ($groups as $g): ?>
                        <span class="badge bg-primary bg-opacity-10 text-primary me-1 mb-1"><?= e($g['name']) ?></span>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="col-md-3">
                <div class="text-muted text-uppercase small fw-semibold mb-1">Method</div>
                <?php if ($mode === 'mine'): ?>
                    <div>
                        <i class="bi bi-database-fill-check me-1 text-success"></i>
                        Data-mined <strong><?= number_format($minedCount) ?></strong> recent ticket
                        subject<?= $minedCount === 1 ? '' : 's' ?>
                    </div>
                <?php else: ?>
                    <div>
                        <i class="bi bi-lightbulb me-1 text-muted"></i>
                        Organization profile only
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<?php if (empty($suggestions)): ?>
    <div class="card border-0 shadow-sm">
        <div class="card-body text-center py-5">
            <i class="bi bi-check-circle text-success" style="font-size:2.5rem;"></i>
            <h5 class="mt-3 fw-bold">Nothing new to suggest</h5>
            <p class="text-muted mb-3">The AI didn't return any skills that aren't already in your setup. Your skill catalogue may already cover the common cases for this organization.</p>
            <a href="/admin/skills" class="btn btn-outline-secondary">Back to Skills</a>
        </div>
    </div>
<?php else: ?>
<form method="POST" action="/admin/skills/suggest">
    <?= csrfField() ?>

    <div class="card border-0 shadow-sm">
        <div class="card-header bg-white d-flex justify-content-between align-items-center py-3">
            <div>
                <h5 class="fw-bold mb-0"><?= count($suggestions) ?> Suggestion<?= count($suggestions) === 1 ? '' : 's' ?></h5>
                <div class="text-muted small">All checked by default — uncheck any you don't want.</div>
            </div>
            <div class="d-flex gap-2">
                <button type="button" class="btn btn-sm btn-outline-secondary" id="selectAllBtn">
                    <i class="bi bi-check2-square me-1"></i>Select All
                </button>
                <button type="button" class="btn btn-sm btn-outline-secondary" id="selectNoneBtn">
                    <i class="bi bi-square me-1"></i>Select None
                </button>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th style="width:42px;"></th>
                        <th style="width:25%;">Skill Name</th>
                        <th>Description</th>
                        <th style="width:25%;">Scope</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($suggestions as $i => $s): ?>
                    <tr class="suggestion-row">
                        <td class="text-center">
                            <input class="form-check-input suggestion-check" type="checkbox"
                                   name="skills[<?= $i ?>][_keep]" value="1" checked
                                   id="keep_<?= $i ?>" aria-label="Include this suggestion">
                        </td>
                        <td>
                            <input type="text" class="form-control form-control-sm"
                                   name="skills[<?= $i ?>][name]"
                                   value="<?= e($s['name']) ?>" maxlength="100" required>
                        </td>
                        <td>
                            <input type="text" class="form-control form-control-sm"
                                   name="skills[<?= $i ?>][description]"
                                   value="<?= e($s['description']) ?>" maxlength="500"
                                   placeholder="Optional description">
                        </td>
                        <td>
                            <select class="form-select form-select-sm" name="skills[<?= $i ?>][group_id]">
                                <option value="" <?= empty($s['group_id']) ? 'selected' : '' ?>>Global (admin-only)</option>
                                <?php foreach ($groups as $g): ?>
                                <option value="<?= (int) $g['id'] ?>"
                                        <?= !empty($s['group_id']) && (int) $s['group_id'] === (int) $g['id'] ? 'selected' : '' ?>>
                                    Owned by: <?= e($g['name']) ?>
                                </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="d-flex gap-2 mt-4">
        <button type="submit" class="btn text-white" style="background:var(--ld-primary);">
            <i class="bi bi-check-lg me-1"></i>Add Selected Skills
        </button>
        <a href="/admin/skills" class="btn btn-outline-secondary">Cancel</a>
        <a href="<?= e($regenerateHref) ?>" class="btn btn-outline-primary ms-auto" title="Ask the AI again with the same settings — results will vary">
            <i class="bi bi-arrow-clockwise me-1"></i>Regenerate
        </a>
    </div>
</form>

<script>
(function () {
    var checks = document.querySelectorAll('.suggestion-check');
    document.getElementById('selectAllBtn').addEventListener('click', function () {
        checks.forEach(function (c) { c.checked = true; });
    });
    document.getElementById('selectNoneBtn').addEventListener('click', function () {
        checks.forEach(function (c) { c.checked = false; });
    });
    // Disable inputs in unchecked rows so the server only receives checked ones.
    function syncRowEnabled(row) {
        var keep = row.querySelector('.suggestion-check').checked;
        row.querySelectorAll('input[type=text], select').forEach(function (el) {
            el.disabled = !keep;
        });
        row.classList.toggle('table-secondary', !keep);
    }
    document.querySelectorAll('.suggestion-row').forEach(function (row) {
        var cb = row.querySelector('.suggestion-check');
        cb.addEventListener('change', function () { syncRowEnabled(row); });
    });
    // Also re-sync after Select All / None
    ['selectAllBtn', 'selectNoneBtn'].forEach(function (id) {
        document.getElementById(id).addEventListener('click', function () {
            document.querySelectorAll('.suggestion-row').forEach(syncRowEnabled);
        });
    });
})();
</script>
<?php endif; ?>
